/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubscriptionsNewRouteImport } from './routes/subscriptions.new'
import { Route as SubscriptionsIdEditRouteImport } from './routes/subscriptions.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsNewRoute = SubscriptionsNewRouteImport.update({
  id: '/subscriptions/new',
  path: '/subscriptions/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsIdEditRoute = SubscriptionsIdEditRouteImport.update({
  id: '/subscriptions/$id/edit',
  path: '/subscriptions/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/subscriptions/new': typeof SubscriptionsNewRoute
  '/subscriptions/$id/edit': typeof SubscriptionsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/subscriptions/new': typeof SubscriptionsNewRoute
  '/subscriptions/$id/edit': typeof SubscriptionsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/subscriptions/new': typeof SubscriptionsNewRoute
  '/subscriptions/$id/edit': typeof SubscriptionsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/subscriptions/new' | '/subscriptions/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/subscriptions/new' | '/subscriptions/$id/edit'
  id: '__root__' | '/' | '/subscriptions/new' | '/subscriptions/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SubscriptionsNewRoute: typeof SubscriptionsNewRoute
  SubscriptionsIdEditRoute: typeof SubscriptionsIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions/new': {
      id: '/subscriptions/new'
      path: '/subscriptions/new'
      fullPath: '/subscriptions/new'
      preLoaderRoute: typeof SubscriptionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions/$id/edit': {
      id: '/subscriptions/$id/edit'
      path: '/subscriptions/$id/edit'
      fullPath: '/subscriptions/$id/edit'
      preLoaderRoute: typeof SubscriptionsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SubscriptionsNewRoute: SubscriptionsNewRoute,
  SubscriptionsIdEditRoute: SubscriptionsIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
