/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ImportRouteImport } from './routes/import'
import { Route as SubscriptionsNewRouteImport } from './routes/subscriptions.new'
import { Route as SubscriptionsIdCancelRouteImport } from './routes/subscriptions.$id.cancel'
import { Route as SubscriptionsIdEditRouteImport } from './routes/subscriptions.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsNewRoute = SubscriptionsNewRouteImport.update({
  id: '/subscriptions/new',
  path: '/subscriptions/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsIdCancelRoute = SubscriptionsIdCancelRouteImport.update({
  id: '/subscriptions/$id/cancel',
  path: '/subscriptions/$id/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsIdEditRoute = SubscriptionsIdEditRouteImport.update({
  id: '/subscriptions/$id/edit',
  path: '/subscriptions/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/import': typeof ImportRoute
  '/subscriptions/new': typeof SubscriptionsNewRoute
  '/subscriptions/$id/cancel': typeof SubscriptionsIdCancelRoute
  '/subscriptions/$id/edit': typeof SubscriptionsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/import': typeof ImportRoute
  '/subscriptions/new': typeof SubscriptionsNewRoute
  '/subscriptions/$id/cancel': typeof SubscriptionsIdCancelRoute
  '/subscriptions/$id/edit': typeof SubscriptionsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/import': typeof ImportRoute
  '/subscriptions/new': typeof SubscriptionsNewRoute
  '/subscriptions/$id/cancel': typeof SubscriptionsIdCancelRoute
  '/subscriptions/$id/edit': typeof SubscriptionsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/import'
    | '/subscriptions/new'
    | '/subscriptions/$id/cancel'
    | '/subscriptions/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/import'
    | '/subscriptions/new'
    | '/subscriptions/$id/cancel'
    | '/subscriptions/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/import'
    | '/subscriptions/new'
    | '/subscriptions/$id/cancel'
    | '/subscriptions/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ImportRoute: typeof ImportRoute
  SubscriptionsNewRoute: typeof SubscriptionsNewRoute
  SubscriptionsIdCancelRoute: typeof SubscriptionsIdCancelRoute
  SubscriptionsIdEditRoute: typeof SubscriptionsIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions/new': {
      id: '/subscriptions/new'
      path: '/subscriptions/new'
      fullPath: '/subscriptions/new'
      preLoaderRoute: typeof SubscriptionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions/$id/cancel': {
      id: '/subscriptions/$id/cancel'
      path: '/subscriptions/$id/cancel'
      fullPath: '/subscriptions/$id/cancel'
      preLoaderRoute: typeof SubscriptionsIdCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions/$id/edit': {
      id: '/subscriptions/$id/edit'
      path: '/subscriptions/$id/edit'
      fullPath: '/subscriptions/$id/edit'
      preLoaderRoute: typeof SubscriptionsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ImportRoute: ImportRoute,
  SubscriptionsNewRoute: SubscriptionsNewRoute,
  SubscriptionsIdCancelRoute: SubscriptionsIdCancelRoute,
  SubscriptionsIdEditRoute: SubscriptionsIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
